// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pruebasEntityFramework.Models;

namespace pruebasEntityFramework.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20210612214608_DatosDePrueba")]
    partial class DatosDePrueba
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("pruebasEntityFramework.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.ToTable("CATEGORIAS");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Remera"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Pantalon"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Campera"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Calzado"
                        });
                });

            modelBuilder.Entity("pruebasEntityFramework.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Categoria_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaDeCreacion")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.Property<double>("Precio")
                        .HasColumnType("double");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PRODUCTOS");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria_id = 1,
                            FechaDeCreacion = new DateTime(2021, 6, 12, 18, 46, 7, 989, DateTimeKind.Local).AddTicks(9254),
                            Nombre = "Remera manga larga rallada",
                            Precio = 1200.0,
                            Stock = 13
                        },
                        new
                        {
                            Id = 2,
                            Categoria_id = 1,
                            FechaDeCreacion = new DateTime(2021, 6, 12, 18, 46, 7, 991, DateTimeKind.Local).AddTicks(3335),
                            Nombre = "Remera manga corta estampada",
                            Precio = 1450.0,
                            Stock = 11
                        },
                        new
                        {
                            Id = 3,
                            Categoria_id = 2,
                            FechaDeCreacion = new DateTime(2021, 6, 12, 18, 46, 7, 991, DateTimeKind.Local).AddTicks(3396),
                            Nombre = "Pantalon chino color mostaza",
                            Precio = 4100.0,
                            Stock = 11
                        },
                        new
                        {
                            Id = 4,
                            Categoria_id = 2,
                            FechaDeCreacion = new DateTime(2021, 6, 12, 18, 46, 7, 991, DateTimeKind.Local).AddTicks(3400),
                            Nombre = "Pantalon Jean negro",
                            Precio = 3800.0,
                            Stock = 15
                        },
                        new
                        {
                            Id = 5,
                            Categoria_id = 2,
                            FechaDeCreacion = new DateTime(2021, 6, 12, 18, 46, 7, 991, DateTimeKind.Local).AddTicks(3402),
                            Nombre = "Bermuda color azul",
                            Precio = 1100.0,
                            Stock = 13
                        },
                        new
                        {
                            Id = 6,
                            Categoria_id = 3,
                            FechaDeCreacion = new DateTime(2021, 6, 12, 18, 46, 7, 991, DateTimeKind.Local).AddTicks(3405),
                            Nombre = "Campera parka",
                            Precio = 12500.0,
                            Stock = 4
                        },
                        new
                        {
                            Id = 7,
                            Categoria_id = 4,
                            FechaDeCreacion = new DateTime(2021, 6, 12, 18, 46, 7, 991, DateTimeKind.Local).AddTicks(3407),
                            Nombre = "Zapatilla blanca",
                            Precio = 5800.0,
                            Stock = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
